// Temporary normalized audit events for Dashboard UI development.
// Replace the data source in adminDashboardService.js once the backend audit
// endpoint supplies the same frontend-facing fields.
export const placeholderAuditEvents = [
  {
    id: "audit-placeholder-001",
    occurredAt: "2026-08-13T09:42:00+08:00",
    actorId: "user-001",
    actorName: "Harvey Babia",
    actorRole: "System Administrator",
    actingAs: "System Administrator",
    eventType: "USER_ACCOUNT_CREATED",
    eventLabel: "User Account Created",
    module: "Account Management",
    entityType: "User Account",
    entityId: "user-014",
    target: "Maria Santos",
    summary: "Created a Subject Teacher account for Maria Santos.",
    impact: "Medium",
    schoolYear: null,
    term: null,
    subject: null,
    section: null,
    beforeData: {},
    afterData: { role: "Subject Teacher", account_status: "Active" },
    metadata: { source: "placeholder" },
  },
  {
    id: "audit-placeholder-002",
    occurredAt: "2026-08-13T08:55:00+08:00",
    actorId: "user-001",
    actorName: "Harvey Babia",
    actorRole: "System Administrator",
    actingAs: "System Administrator",
    eventType: "SUBJECT_WEIGHTS_UPDATED",
    eventLabel: "Subject Weights Updated",
    module: "WS Configuration",
    entityType: "Subject Component Weight",
    entityId: "subject-eng",
    target: "English",
    summary: "Updated the grading-component weights for English.",
    impact: "Medium",
    schoolYear: "2026–2027",
    term: null,
    subject: "English",
    section: null,
    beforeData: { written_work: "30%", performance_tasks: "50%", assessment: "20%" },
    afterData: { written_work: "40%", performance_tasks: "40%", assessment: "20%" },
    metadata: { source: "placeholder" },
  },
  {
    id: "audit-placeholder-003",
    occurredAt: "2026-08-12T15:18:00+08:00",
    actorId: "user-007",
    actorName: "Angelica Ramos",
    actorRole: "Subject Teacher",
    actingAs: "Subject Teacher",
    eventType: "GRADE_SHEET_SUBMITTED",
    eventLabel: "Grade Sheet Submitted",
    module: "Grading",
    entityType: "Grade Sheet",
    entityId: "grade-sheet-108",
    target: "Mathematics 8 — Rizal",
    summary: "Submitted the Term 1 Mathematics grade sheet.",
    impact: "Medium",
    schoolYear: "2026–2027",
    term: "Term 1",
    subject: "Mathematics 8",
    section: "Rizal",
    beforeData: { workflow_status: "Draft", lock_status: "Editable" },
    afterData: { workflow_status: "Submitted", lock_status: "Submission Read Only" },
    metadata: { source: "placeholder" },
  },
  {
    id: "audit-placeholder-004",
    occurredAt: "2026-08-12T13:04:00+08:00",
    actorId: "user-009",
    actorName: "Carla Mendoza",
    actorRole: "Subject Teacher",
    actingAs: "Subject Teacher",
    eventType: "GRADE_SHEET_RECALLED",
    eventLabel: "Grade Sheet Recalled",
    module: "Grading",
    entityType: "Grade Sheet",
    entityId: "grade-sheet-104",
    target: "Science 9 — Mahogany",
    summary: "Recalled a submitted Science grade sheet before the deadline.",
    impact: "Low",
    schoolYear: "2026–2027",
    term: "Term 1",
    subject: "Science 9",
    section: "Mahogany",
    beforeData: { workflow_status: "Submitted" },
    afterData: { workflow_status: "Draft" },
    metadata: { source: "placeholder" },
  },
  {
    id: "audit-placeholder-005",
    occurredAt: "2026-08-11T16:36:00+08:00",
    actorId: "user-005",
    actorName: "Mark Santos",
    actorRole: "Subject Teacher",
    actingAs: "Subject Teacher",
    eventType: "GRADE_SHEET_CORRECTION_RESUBMITTED",
    eventLabel: "Grade Sheet Correction Resubmitted",
    module: "Grading",
    entityType: "Grade Sheet",
    entityId: "grade-sheet-088",
    target: "English 9 — Mahogany",
    summary: "Resubmitted the corrected Term 1 English grade sheet for Mahogany.",
    impact: "Medium",
    schoolYear: "2026–2027",
    term: "Term 1",
    subject: "English 9",
    section: "Mahogany",
    beforeData: { workflow_status: "Draft", lock_status: "Temporarily Reopened" },
    afterData: { workflow_status: "Submitted", lock_status: "Term Locked" },
    metadata: { source: "placeholder" },
  },
  {
    id: "audit-placeholder-006",
    occurredAt: "2026-08-10T23:59:00+08:00",
    actorId: null,
    actorName: "Auralis System",
    actorRole: "System",
    actingAs: "Automated Grade Lock",
    eventType: "TERM_AUTOMATICALLY_LOCKED",
    eventLabel: "Term Automatically Locked",
    module: "Grade Lock",
    entityType: "Academic Term",
    entityId: "term-2026-1",
    target: "Term 1",
    summary: "Automatically locked Term 1 grading sheets when the deadline elapsed.",
    impact: "High",
    schoolYear: "2026–2027",
    term: "Term 1",
    subject: null,
    section: null,
    beforeData: { status: "Ongoing" },
    afterData: { status: "Completed", lock_status: "Term Locked" },
    metadata: { source: "placeholder", trigger: "deadline" },
  },
  {
    id: "audit-placeholder-007",
    occurredAt: "2026-08-09T10:15:00+08:00",
    actorId: "user-001",
    actorName: "Harvey Babia",
    actorRole: "System Administrator",
    actingAs: "System Administrator",
    eventType: "REOPENING_REQUEST_APPROVED",
    eventLabel: "Reopening Request Approved",
    module: "Grade Lock",
    entityType: "Grade Reopen Request",
    entityId: "reopen-request-021",
    target: "Filipino 8 — Narra",
    summary: "Approved temporary correction access for a locked Filipino grade sheet.",
    impact: "High",
    schoolYear: "2026–2027",
    term: "Term 1",
    subject: "Filipino 8",
    section: "Narra",
    beforeData: { request_status: "Pending" },
    afterData: { request_status: "Approved", access_duration: "1 hour" },
    metadata: {
      source: "placeholder",
      reason: "Incorrect score encoded for one learner",
    },
  },
  {
    id: "audit-placeholder-008",
    occurredAt: "2026-08-09T11:15:00+08:00",
    actorId: null,
    actorName: "Auralis System",
    actorRole: "System",
    actingAs: "Automated Reopening Control",
    eventType: "TEMPORARY_REOPENING_EXPIRED",
    eventLabel: "Temporary Reopening Expired",
    module: "Grade Lock",
    entityType: "Temporary Reopening",
    entityId: "temporary-reopening-021",
    target: "Filipino 8 — Narra",
    summary: "Automatically closed temporary editing access after one hour.",
    impact: "Medium",
    schoolYear: "2026–2027",
    term: "Term 1",
    subject: "Filipino 8",
    section: "Narra",
    beforeData: { status: "Active" },
    afterData: { status: "Expired" },
    metadata: { source: "placeholder", trigger: "expiration" },
  },
  {
    id: "audit-placeholder-010",
    occurredAt: "2026-03-18T09:30:00+08:00",
    actorId: "user-001",
    actorName: "Harvey Babia",
    actorRole: "System Administrator",
    actingAs: "System Administrator",
    eventType: "SUBJECT_WEIGHTS_UPDATED",
    eventLabel: "Subject Weights Updated",
    module: "WS Configuration",
    entityType: "Subject Component Weight",
    entityId: "subject-science",
    target: "Science",
    summary: "Updated the completed school year's Science component weights.",
    impact: "Medium",
    schoolYear: "2025–2026",
    term: null,
    subject: "Science",
    section: null,
    beforeData: { written_work: "30%", performance_tasks: "50%", assessment: "20%" },
    afterData: { written_work: "40%", performance_tasks: "40%", assessment: "20%" },
    metadata: { source: "placeholder" },
  },
];
